// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcsghorkukjfbddtrdxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjc2dob3JrdWtqZmJkZHRyZHh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTYxMzAsImV4cCI6MjA2NzQ5MjEzMH0.G7C11fKhbtSzEFwF2jZAWJLjIT24Me8VA2QfP6LvNx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});